//! Regression: a play permission that states its own lifetime ("you may play
//! that card FOR AS LONG AS you control this creature") is a lingering
//! permission (CR 611.2a), not a resolution-time "may" offer (CR 608.2d).
//!
//! Bug: `lower_imperative_clause` stripped the trailing duration and assigned it
//! to `ParsedEffectClause.duration` alone, bypassing the shared
//! `with_clause_duration` building block that also patches the duration slot
//! INSIDE effects that own one. `Effect::CastFromZone.duration` therefore stayed
//! `None`, and the two consumers this class reaches both went wrong:
//!
//!   * `is_lingering_cast_from_zone` (parser assembly) stopped recognizing the
//!     clause as a deferred grant, so the clause's "may" was promoted to
//!     `AbilityDefinition.optional` — the engine paused resolution with a
//!     `WaitingFor::OptionalEffectChoice`, and declining destroyed the grant
//!     outright, stranding the card in exile forever.
//!   * `record_lingering_permissions` (engine) reads the same effect field for
//!     the granted permission's expiry, so an accepted grant was stamped with no
//!     duration at all.
//!
//! F3 — the field gained a value it never carried, so its five reader sites were
//! walked: `assembly.rs:2384`, `cast_from_zone.rs:733`, `:764`, `:1380`,
//! `ability_rw.rs:3390`. The first and fourth are the two above. The other three
//! cannot move for any input:
//!
//!   * `cast_from_zone.rs:733` and `:764` both require `duration.is_none()`, so
//!     populating the field can only ever CLOSE them, never open one.
//!   * `ability_rw.rs:3390` feeds the duration to `legacy_duration`
//!     (`ability_rw.rs:2115`), a two-armed match: `ForAsLongAs` delegates to
//!     `legacy_static_condition`, where the `Unrecognized` conditions this fix
//!     installs are a `false` arm (`:2099`); every other variant is `false`
//!     outright (`:2118-2127`). No duration this fix can install moves it.
//!
//! Fix (first half): route that assignment through `with_clause_duration`.
//!
//! SECOND DEFECT, same class, found by playtest and by review: recording the
//! duration is not enough, because nothing ever ENFORCED it.
//! `layers::prune_host_left_effects` retains only
//! `state.transient_continuous_effects`, and `CastingPermission::ExileWithAltCost`
//! carried no granting-source identity to prune against — so a permission
//! stamped `Duration::UntilHostLeavesPlay` outlived its host indefinitely,
//! turning a prompt bug into a rules-incorrect standing permission.
//!
//! Fix (second half): `ExileWithAltCost` gains `source_id`, stamped in
//! `record_lingering_permissions` and `grant_permission::resolve` exactly where
//! the `PlayFromExile` land companion already stamped its own; and
//! `layers::prune_host_left_casting_permissions` revokes both halves from the
//! battlefield-exit lifecycle in `zones::apply_zone_exit_cleanup`, beside the
//! existing `prune_host_left_effects` call.
//!
//! Two members of the repaired set are covered, reached by different routes: a
//! top-of-library impulse with the "that card" anaphor (Gwen Stacy) and a
//! targeted graveyard exile with the "it" anaphor (Victor Mancha, Runaway).
//! Both carry `Duration::UntilHostLeavesPlay`. The set's two
//! `Duration::ForAsLongAs` members (Spelljack, Resourceful Collector) are NOT
//! covered, and the reason is that neither reaches a usable fixture: Spelljack's
//! countered card lands in exile with no permission recorded at all, and
//! Resourceful Collector's grant hangs off a random end-step pick. Whether the
//! Spelljack shortfall is a real defect or an artefact of a synthetic stack
//! entry is not isolated, so no claim is made about it.
//!
//! CR 611.2a: a continuous effect generated by the resolution of a spell or
//! ability "lasts as long as stated by the spell or ability creating it".
//! CR 611.2b: the "for as long as . . ." wording is exactly this class; its own
//! example is Master Thief's "for as long as you control this creature", the
//! same shape as Gwen Stacy's and Victor Mancha's.
//! CR 608.2d: a resolution-time choice is one the player "announces … while
//! applying the effect" — the shape this class was wrongly classified as.
//! CR 601.3: "A player can begin to cast a spell only if a rule or effect allows
//! that player to cast it" — what the recorded permission provides.
//! CR 305.1: playing a land "is a special action … it is never a spell", so the
//! land companion of a `mode: Play` grant is authorized by a different rule than
//! its spell half.

use engine::ai_support::legal_actions;
use engine::game::scenario::{GameRunner, GameScenario, P0};
use engine::parser::oracle::parse_oracle_text;
use engine::types::ability::{
    AbilityDefinition, CastingPermission, Duration, Effect, FilterProp, LibraryPosition,
    QuantityExpr, TargetFilter, TypedFilter,
};
use engine::types::actions::GameAction;
use engine::types::game_state::WaitingFor;
use engine::types::identifiers::ObjectId;
use engine::types::mana::ManaCost;
use engine::types::phase::Phase;
use engine::types::zones::Zone;

/// Verbatim Oracle text (`client/public/card-data.json`, key `gwen stacy`).
const GWEN_STACY: &str =
    "When Gwen Stacy enters, exile the top card of your library. You may play \
     that card for as long as you control this creature.\n{2}{U}{R}{W}: Transform Gwen Stacy. \
     Activate only as a sorcery.";

/// Verbatim Oracle text (`client/public/card-data.json`, key
/// `victor mancha, runaway`).
const VICTOR_MANCHA: &str = "When Victor Mancha enters, exile target card from your graveyard. \
     You may play it for as long as you control Victor Mancha.";

/// Verbatim Oracle text (`client/public/card-data.json`, key
/// `the day of the doctor`).
const DAY_OF_THE_DOCTOR: &str =
    "(As this Saga enters and after your draw step, add a lore counter. Sacrifice after IV.)\n\
     I, II, III — Exile cards from the top of your library until you exile a legendary card. \
     You may play that card for as long as this Saga remains on the battlefield. Put the rest of \
     those exiled cards on the bottom of your library in a random order.\n\
     IV — Choose up to three Doctors. You may exile all other creatures. If you do, this Saga \
     deals 13 damage to you.";

fn zone_of(runner: &GameRunner, id: ObjectId) -> Zone {
    runner
        .state()
        .objects
        .get(&id)
        .expect("object present")
        .zone
}

fn can_cast(runner: &GameRunner, id: ObjectId) -> bool {
    legal_actions(runner.state())
        .iter()
        .any(|action| matches!(action, GameAction::CastSpell { object_id, .. } if *object_id == id))
}

/// CR 305.1: a land is PLAYED, never cast, so the land companion of a
/// `mode: Play` grant surfaces as `GameAction::PlayLand` — a different action
/// than `can_cast` above inspects.
fn can_play_land(runner: &GameRunner, id: ObjectId) -> bool {
    legal_actions(runner.state())
        .iter()
        .any(|action| matches!(action, GameAction::PlayLand { object_id, .. } if *object_id == id))
}

/// Verbatim Oracle text (`client/public/card-data.json`, key `murder`), reduced
/// to its single clause: the test needs a production removal path, not Murder.
const DESTROY_TARGET_CREATURE: &str = "Destroy target creature.";

/// Remove `victim` from the battlefield by casting and resolving a removal
/// spell, so the battlefield-exit lifecycle in `zones::apply_zone_exit_cleanup`
/// actually runs. CR 701.8a: to destroy a permanent is to "move it from the
/// battlefield to its owner's graveyard", done here during the removal spell's
/// own resolution; CR 701.8b lists the only other route as the state-based
/// actions for lethal or deathtouch damage, neither of which is in play. A direct
/// `zones::move_to_zone` would skip the lifecycle and make the assertions below
/// vacuous.
fn destroy_via_removal_spell(runner: &mut GameRunner, removal: ObjectId, victim: ObjectId) {
    runner.cast(removal).target_object(victim).commit();
    runner.advance_until_stack_empty();
}

/// The durations recorded on `id`'s casting permissions, in grant order.
fn recorded_permission_durations(runner: &GameRunner, id: ObjectId) -> Vec<Option<Duration>> {
    runner.state().objects[&id]
        .casting_permissions
        .iter()
        .map(|permission| match permission {
            CastingPermission::ExileWithAltCost { duration, .. } => duration.clone(),
            CastingPermission::PlayFromExile { duration, .. } => Some(duration.clone()),
            _ => None,
        })
        .collect()
}

/// Drive resolution to a stable point, declining every optional-effect prompt
/// that appears. Returns whether any prompt was offered at all — the decline is
/// what the player did in the field report, and it is what destroyed the grant.
fn settle_declining_optionals(runner: &mut GameRunner) -> bool {
    let mut saw_optional = false;
    loop {
        runner.advance_until_stack_empty();
        match runner.state().waiting_for.clone() {
            WaitingFor::OptionalEffectChoice { .. } => {
                saw_optional = true;
                runner
                    .act(GameAction::DecideOptionalEffect { accept: false })
                    .expect("declining an offered optional effect must be accepted");
            }
            _ => break,
        }
    }
    saw_optional
}

/// CR 611.2a: "for as long as you control this creature" states the permission's
/// own lifetime, so resolution offers NO choice and the exiled card stays
/// castable — and the permission is recorded carrying that stated lifetime.
///
/// DISCRIMINATING ASSERTIONS: `!saw_optional`, `can_cast(exiled)`, and the
/// recorded `Duration::UntilHostLeavesPlay`. Reverting the
/// `with_clause_duration` routing leaves `Effect::CastFromZone.duration` empty,
/// `is_lingering_cast_from_zone` stops matching, the clause's "may" becomes
/// `AbilityDefinition.optional`, and all three flip — a prompt appears, and
/// declining it strands the card in exile with no permission at all.
///
/// Positive reach-guard: `zone_of(exiled) == Exile` proves the enters trigger
/// really resolved, so a green run is not a vacuous no-op.
///
/// NOT PROVEN HERE: that the recorded `UntilHostLeavesPlay` is ever *enforced*.
/// That is the subject of `host_departure_revokes_the_lasting_cast_permission`
/// and `host_departure_revokes_the_lasting_land_play_companion` below; this
/// test stops while the host is still on the battlefield on purpose, so a
/// failure here localizes to the parse fix and not to the lifecycle.
#[test]
fn lasting_play_permission_is_not_a_declinable_resolution_offer() {
    let mut scenario = GameScenario::new();
    scenario.at_phase(Phase::PreCombatMain);
    let impulse_card = scenario
        .add_spell_to_library_top(P0, "Library Top Card", false)
        .with_mana_cost(ManaCost::zero())
        .id();
    let gwen = scenario
        .add_creature_to_hand_from_oracle(P0, "Gwen Stacy", 2, 2, GWEN_STACY)
        .with_mana_cost(ManaCost::zero())
        .id();
    let mut runner = scenario.build();

    runner.cast(gwen).commit();
    let saw_optional = settle_declining_optionals(&mut runner);

    // Reach-guards: the enters trigger resolved, and the stated lifetime holds.
    assert_eq!(
        zone_of(&runner, impulse_card),
        Zone::Exile,
        "Gwen Stacy's enters trigger must exile the top card of the library"
    );
    assert_eq!(
        zone_of(&runner, gwen),
        Zone::Battlefield,
        "Gwen Stacy must be on the battlefield — the permission's stated lifetime"
    );

    assert!(
        !saw_optional,
        "CR 611.2a: a permission that states its own lifetime is not a CR 608.2d \
         resolution-time choice, so no prompt may be offered"
    );
    assert!(
        can_cast(&runner, impulse_card),
        "the exiled card must be castable from exile through the standing permission"
    );
    assert_eq!(
        recorded_permission_durations(&runner, impulse_card),
        vec![
            Some(Duration::UntilHostLeavesPlay),
            Some(Duration::UntilHostLeavesPlay)
        ],
        "CR 601.3 + CR 305.1 + CR 611.2a: both halves of a `mode: Play` grant (the spell \
         permission and its land companion) must carry the stated lifetime"
    );
}

/// A second member of the same class, reached by a different route: a TARGETED
/// graveyard exile rather than a top-of-library impulse, with the "it" anaphor
/// rather than "that card". Same stated lifetime, same defect before the fix.
///
/// DISCRIMINATING ASSERTIONS: `!saw_optional` and `can_cast(exiled)`. Both flip
/// on revert — the promoted "may" pauses resolution and the decline destroys the
/// grant.
///
/// Positive reach-guard: the targeted card moved Graveyard -> Exile, so the
/// permission clause was reached.
#[test]
fn lasting_play_permission_covers_the_targeted_graveyard_exile_member() {
    let mut scenario = GameScenario::new();
    scenario.at_phase(Phase::PreCombatMain);
    let buried = scenario
        .add_spell_to_graveyard(P0, "Buried Card", false)
        .with_mana_cost(ManaCost::zero())
        .id();
    let victor = scenario
        .add_creature_to_hand_from_oracle(P0, "Victor Mancha, Runaway", 3, 3, VICTOR_MANCHA)
        .with_mana_cost(ManaCost::zero())
        .id();
    let mut runner = scenario.build();

    runner.cast(victor).commit();
    let saw_optional = settle_declining_optionals(&mut runner);

    // Reach-guards: the enters trigger resolved and Victor is still out.
    assert_eq!(
        zone_of(&runner, buried),
        Zone::Exile,
        "Victor Mancha's enters trigger must exile the targeted graveyard card"
    );
    assert_eq!(
        zone_of(&runner, victor),
        Zone::Battlefield,
        "Victor Mancha must be on the battlefield — the permission's stated lifetime"
    );

    assert!(
        !saw_optional,
        "CR 611.2a: \"you may play it for as long as you control Victor Mancha\" states the \
         permission's lifetime — no CR 608.2d resolution-time choice may be offered"
    );
    assert!(
        can_cast(&runner, buried),
        "the exiled card must be castable from exile through the standing permission"
    );
}

/// Collect every `CastFromZone` node in an ability chain, in walk order.
fn cast_from_zone_nodes(a: &AbilityDefinition, out: &mut Vec<AbilityDefinition>) {
    if matches!(&*a.effect, Effect::CastFromZone { .. }) {
        out.push(a.clone());
    }
    if let Some(sub) = &a.sub_ability {
        cast_from_zone_nodes(sub, out);
    }
    if let Some(els) = &a.else_ability {
        cast_from_zone_nodes(els, out);
    }
}

/// CR 608.2c: "later text on the card may modify the meaning of earlier text" —
/// "the rest of those exiled cards" means every card this `ExileFromTopUntil`
/// exiled EXCEPT the hit the permission covers, whether or not that permission
/// is a resolution-time offer.
///
/// This pins the second half of the fix. Removing the spurious `optional` (the
/// first half) would otherwise have silently disarmed the Jodah bottom-cleanup
/// rewrite, because `is_exile_until_cast_bottom_cleanup` was consulted only for
/// an `optional` cast — the cleanup would fall back to the parser-default
/// `TrackedSet` selector with `count: 1`, which no longer denotes "the rest".
///
/// DISCRIMINATING ASSERTIONS: the cleanup's `target` and `count`. Reverting the
/// decoupling turns them into `TargetFilter::TrackedSet { id: 0 }` and
/// `QuantityExpr::Fixed { value: 1 }` — measured, not assumed.
/// `else_ability.is_none()` is narrower: it pins the inner `if chain.optional`
/// guard alone (a wholesale revert also leaves it `None`), and it says that a
/// standing permission has no decline branch (CR 608.2d), so the duplicate copy
/// the old code stashed for the chain scanners must be gone.
///
/// Positive reach-guard: three chapter chains are found and each carries a
/// `CastFromZone` with `optional == false` — the fix's first half ran, which is
/// exactly the precondition that used to disarm the rewrite.
///
/// SCOPE — this is a PARSE assertion, deliberately, and here is what it does NOT
/// say. It does not assert that a card moves: verified against the live
/// deployment of `main`, The Day of the Doctor leaves the exiled remainder in
/// exile at runtime BOTH with and without this change, so the delivery of this
/// cleanup is independently broken and this diff neither causes nor repairs it.
/// The pin exists so that the correct instruction keeps being emitted.
///
/// It also pins ONE of the two call sites. The Day of the Doctor reaches
/// `assembly.rs`'s `normalize_linked_exile_cast_pair`; the sibling site in
/// `sequence.rs` (`append_definition_to_sub_chain`) is edited for consistency
/// with no demonstrated reachable input. Four of its five callers build the
/// trailing definition themselves and none produces the
/// `PutAtLibraryPosition { target: TrackedSet | TrackedSetFiltered }` shape the
/// gate requires (`sequence.rs:4879` builds `TargetFilter::Any`; the others pass
/// `ChangeZoneAll` / `GrantCastingPermission` bodies). The fifth
/// (`sequence.rs:4847`) forwards a pre-existing tail whose shape is NOT under
/// the caller's control, but it passes a `ChangeZone` as the chain head, and the
/// gate's first check demands an `ExileFromTopUntil { NextMatches }` head
/// (`lower.rs:930-938`) — so it short-circuits whatever the tail is. Leaving the
/// two sites answering the same question differently would be the worse defect,
/// so the edit stays and is named here rather than tested.
#[test]
fn the_rest_of_those_exiled_cards_survives_the_removed_optionality() {
    let parsed = parse_oracle_text(
        DAY_OF_THE_DOCTOR,
        "The Day of the Doctor",
        &[],
        &["Enchantment".to_string()],
        &["Saga".to_string()],
    );

    let mut nodes = vec![];
    for ability in &parsed.abilities {
        cast_from_zone_nodes(ability, &mut nodes);
    }
    for trigger in &parsed.triggers {
        if let Some(execute) = &trigger.execute {
            cast_from_zone_nodes(execute, &mut nodes);
        }
    }

    // Reach-guard: chapters I, II and III each lower to their own chain.
    assert_eq!(
        nodes.len(),
        3,
        "the I, II, III chapter ability must lower to one cast-from-zone chain per chapter"
    );

    let expected_target = TargetFilter::And {
        filters: vec![
            TargetFilter::ExiledBySource,
            TargetFilter::Typed(TypedFilter::default().properties(vec![
                FilterProp::DistinctFrom {
                    reference: Box::new(TargetFilter::ParentTarget),
                },
            ])),
        ],
    };

    for (chapter, node) in nodes.iter().enumerate() {
        assert!(
            !node.optional,
            "chapter {} — a stated-lifetime permission is not a resolution-time choice",
            chapter + 1
        );
        assert!(
            node.else_ability.is_none(),
            "chapter {} — a standing permission has no decline branch, so no duplicate \
             cleanup may be stashed as one (CR 608.2d)",
            chapter + 1
        );
        let cleanup = node
            .sub_ability
            .as_deref()
            .expect("the bottom cleanup must hang under the cast node");
        let Effect::PutAtLibraryPosition {
            target,
            count,
            position,
        } = &*cleanup.effect
        else {
            panic!("chapter {} — expected the bottom cleanup", chapter + 1);
        };
        assert_eq!(*position, LibraryPosition::Bottom);
        assert_eq!(
            *target,
            expected_target,
            "chapter {} — \"the rest\" is every card exiled by this source EXCEPT the hit",
            chapter + 1
        );
        assert_eq!(
            *count,
            QuantityExpr::Fixed { value: 0 },
            "chapter {} — count 0 is the resolver's \"every matching card\" placeholder",
            chapter + 1
        );
    }
}

/// CR 611.2a + CR 400.7: the stated lifetime is not decoration — when the named
/// permanent leaves the battlefield the permission ENDS. Gwen Stacy's grant
/// lasts "for as long as you control this creature"; the parser maps that
/// wording to `Duration::UntilHostLeavesPlay` (pinned by
/// `parser::oracle_nom::duration::test_for_as_long_as_you_control_maps_to_until_host_leaves`).
///
/// SCOPE: that mapping is narrower than the printed wording, and this test is
/// scoped to the mapping, not to CR 611.2b. "For as long as you CONTROL ~" also
/// ends when control changes with the permanent still on the battlefield — the
/// exact case CR 611.2b works through in its Master Thief example. Neither the
/// mapping nor this prune covers it; a control-change exit is a pre-existing
/// gap in the parser's duration choice, untouched here.
///
/// DISCRIMINATING ASSERTIONS: `!can_cast(exiled)` and the now-empty permission
/// list, both taken AFTER Gwen dies. Before this fix the exiled card stayed
/// castable forever: `layers::prune_host_left_effects` retains only
/// `state.transient_continuous_effects`, and `ExileWithAltCost` carried no
/// granting-source id to prune against. Reverting either half of the fix — the
/// `source_id` stamp in `record_lingering_permissions` or the
/// `prune_host_left_casting_permissions` call in `zones` — restores the
/// permission and fails this test.
///
/// Positive reach-guards, all three needed for a green run to mean anything:
/// the card reached exile, it WAS castable while Gwen lived, and Gwen actually
/// reached the graveyard through the removal spell.
#[test]
fn host_departure_revokes_the_lasting_cast_permission() {
    let mut scenario = GameScenario::new();
    scenario.at_phase(Phase::PreCombatMain);
    let impulse_card = scenario
        .add_spell_to_library_top(P0, "Library Top Card", false)
        .with_mana_cost(ManaCost::zero())
        .id();
    let gwen = scenario
        .add_creature_to_hand_from_oracle(P0, "Gwen Stacy", 2, 2, GWEN_STACY)
        .with_mana_cost(ManaCost::zero())
        .id();
    let removal = scenario
        .add_spell_to_hand_from_oracle(P0, "Removal", true, DESTROY_TARGET_CREATURE)
        .with_mana_cost(ManaCost::zero())
        .id();
    let mut runner = scenario.build();

    runner.cast(gwen).commit();
    settle_declining_optionals(&mut runner);

    // Reach-guard 1 + 2: the grant exists and is live while the host is out.
    assert_eq!(
        zone_of(&runner, impulse_card),
        Zone::Exile,
        "reach-guard: Gwen Stacy's enters trigger must exile the top card"
    );
    assert!(
        can_cast(&runner, impulse_card),
        "reach-guard: the exiled card must be castable WHILE Gwen is on the battlefield — \
         otherwise the post-death assertion below proves nothing"
    );

    destroy_via_removal_spell(&mut runner, removal, gwen);

    // Reach-guard 3: the host really left through the production path.
    assert_eq!(
        zone_of(&runner, gwen),
        Zone::Graveyard,
        "reach-guard: the removal spell must actually kill Gwen Stacy"
    );

    assert!(
        !can_cast(&runner, impulse_card),
        "CR 611.2a: 'for as long as you control this creature' ends when that creature \
         leaves the battlefield — the exiled card must no longer be castable. \
         gwen={gwen:?} exiled={impulse_card:?} left_over={:#?}",
        runner.state().objects[&impulse_card].casting_permissions
    );
    assert_eq!(
        recorded_permission_durations(&runner, impulse_card),
        Vec::<Option<Duration>>::new(),
        "CR 611.2a + CR 400.7: both halves of the grant are revoked by the departing host, \
         leaving no casting permission behind"
    );
}

/// CR 305.1: the same grant's LAND half. "You may play that card" authorizes a
/// land through `GameAction::PlayLand`, a different action than the spell half,
/// carried by a separate `CastingPermission::PlayFromExile` companion. Revoking
/// only one half would leave a land playable from exile after its granting
/// permanent died.
///
/// DISCRIMINATING ASSERTION: `!can_play_land(exiled)` after Gwen dies, guarded
/// by the same assertion returning true before she does.
#[test]
fn host_departure_revokes_the_lasting_land_play_companion() {
    let mut scenario = GameScenario::new();
    scenario.at_phase(Phase::PreCombatMain);
    let top_land = scenario.add_card_to_library_top(P0, "Library Top Land");
    let gwen = scenario
        .add_creature_to_hand_from_oracle(P0, "Gwen Stacy", 2, 2, GWEN_STACY)
        .with_mana_cost(ManaCost::zero())
        .id();
    let removal = scenario
        .add_spell_to_hand_from_oracle(P0, "Removal", true, DESTROY_TARGET_CREATURE)
        .with_mana_cost(ManaCost::zero())
        .id();
    let mut runner = scenario.build();

    // The library-top card is a bare object; make it a land in BOTH the live and
    // the base type sets so the layer rebuild cannot revert it (the scenario
    // builders have no library-top land constructor).
    {
        let obj = runner
            .state_mut()
            .objects
            .get_mut(&top_land)
            .expect("library top card present");
        obj.card_types
            .core_types
            .push(engine::types::card_type::CoreType::Land);
        obj.base_card_types = obj.card_types.clone();
    }

    runner.cast(gwen).commit();
    settle_declining_optionals(&mut runner);

    assert_eq!(
        zone_of(&runner, top_land),
        Zone::Exile,
        "reach-guard: Gwen Stacy's enters trigger must exile the top card"
    );
    assert!(
        can_play_land(&runner, top_land),
        "reach-guard: CR 305.1 — the exiled land must be playable WHILE Gwen is on the \
         battlefield, or the post-death assertion below proves nothing"
    );

    destroy_via_removal_spell(&mut runner, removal, gwen);

    assert_eq!(
        zone_of(&runner, gwen),
        Zone::Graveyard,
        "reach-guard: the removal spell must actually kill Gwen Stacy"
    );
    assert!(
        !can_play_land(&runner, top_land),
        "CR 305.1 + CR 611.2a: the land companion of the grant ends with its host, so no \
         PlayLand action may remain"
    );
}
